stages: 
  - test
  - build  
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - $Env:JAVA_HOME = 'C:\Java\bin
    - echo "Compiling the code..."  
    - mvn clean package
    - echo "Compile complete."
  artifacts:
    name: "Executavel-Projeto-de-Integracao"
    paths:
    - target\jfx\native\*.exe
    
unit-test-job:
  stage: test    
  script:
    - $Env:JAVA_HOME = 'C:\Java'
    - mvn clean test

deploy-job:      
  stage: deploy
  script:
    - echo "Deploying application..."
    - copy target\jfx\native\*.exe "\\DESKTOP-RMNOSNV\Deploy" 
    - echo "Deploy finshed successfully"
