stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - $Env:JAVA_HOME = 'C:\Java\jdk1.8.0_51'
    - echo $JAVA_HOME
    - echo "Compiling the code..."  
    - mvn clean package
    - echo "Compile complete."
  artifacts:
    name: "Executavel-Projeto-de-Integracao"
    paths:
    - target\jfx\native\*.exe
    
unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests..."
    - mvn clean test

deploy-job:      
  stage: deploy
  script:
    - echo "Deploying application..."
    - copy target\jfx\native\*.exe "\\DESKTOP-RMNOSNV\Deploy" 
    - echo "Aplicação deploiada"
